docs_dir: blog
site_dir: docs
site_url: https://spaceshaman.github.io/
site_name: SpaceBlog
site_author: SpaceShaman
site_description: A blog about technology, programming, machine learning, and other stuff.

theme:
  name: material
  custom_dir: overrides
  palette: 
    scheme: dark
  features:
    - navigation.sections
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
plugins:
  - blog:
      blog_dir: .
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
      comments_path: "#__comments"
  - search

extra:
  homepage: https://spaceshaman.github.io/

extra_css:
- stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences